# Generated by Django 4.2.3 on 2023-08-12 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=4, verbose_name='요청 종류')),
                ('content', models.TextField(verbose_name='요청 내용')),
                ('mentiLatitude', models.IntegerField(verbose_name='멘티 위도')),
                ('mentiLongitude', models.IntegerField(verbose_name='멘티 경도')),
                ('mentoLatitude', models.IntegerField(default=0, verbose_name='멘토 위도')),
                ('mentoLongitude', models.IntegerField(default=0, verbose_name='멘토 경도')),
                ('requestTime', models.DateTimeField(auto_now_add=True, verbose_name='요청시간')),
                ('acceptTime', models.DateTimeField(verbose_name='수락시간')),
                ('menti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentis', to=settings.AUTH_USER_MODEL)),
                ('mento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
