# Generated by Django 4.2.3 on 2023-08-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='acceptTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수락시간'),
        ),
        migrations.AlterField(
            model_name='request',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='요청 내용'),
        ),
    ]
