# Generated by Django 4.2.3 on 2023-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_request_accepttime_alter_request_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='content',
            field=models.TextField(blank=True, verbose_name='요청 내용'),
        ),
    ]
