# Generated by Django 4.2.3 on 2023-08-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='mentiLatitude',
            field=models.DecimalField(decimal_places=20, max_digits=23, verbose_name='멘티 위도'),
        ),
        migrations.AlterField(
            model_name='request',
            name='mentiLongitude',
            field=models.DecimalField(decimal_places=20, max_digits=24, verbose_name='멘티 경도'),
        ),
        migrations.AlterField(
            model_name='request',
            name='mentoLatitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23, verbose_name='멘토 위도'),
        ),
        migrations.AlterField(
            model_name='request',
            name='mentoLongitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23, verbose_name='멘토 경도'),
        ),
    ]
