# Generated by Django 4.2.3 on 2023-08-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_mentilatitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='mentoLatitude',
        ),
        migrations.RemoveField(
            model_name='request',
            name='mentoLongitude',
        ),
    ]
